// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn1zvJqn6b7s4NIk9uasA_VrlEbrTJ9Gw',
    appId: '1:616379006074:web:5c4f93a46d373c98544fc3',
    messagingSenderId: '616379006074',
    projectId: 'gotravel-rd',
    authDomain: 'gotravel-rd.firebaseapp.com',
    storageBucket: 'gotravel-rd.firebasestorage.app',
    measurementId: 'G-WLHH606SXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxOlcyYINjqN4KxkN5jKDIJiGG_8VdGkg',
    appId: '1:616379006074:android:8c7c0791423aeacc544fc3',
    messagingSenderId: '616379006074',
    projectId: 'gotravel-rd',
    storageBucket: 'gotravel-rd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClaLkiUjJu7Z82atDsufWtStmU6xyBQEk',
    appId: '1:616379006074:ios:8bf4ae9f894ef69c544fc3',
    messagingSenderId: '616379006074',
    projectId: 'gotravel-rd',
    storageBucket: 'gotravel-rd.firebasestorage.app',
    androidClientId: '616379006074-u37k74oqc8s4ob62bivgq88vm4rm6anp.apps.googleusercontent.com',
    iosClientId: '616379006074-kjmh3g81gdqrehjv1rgh4tvu8qprn94s.apps.googleusercontent.com',
    iosBundleId: 'com.unapec.gotravelrd',
  );
}
